language: node_js
node_js:
  - "7"
script:
  - echo "Deploying!!"
  - npm install
install:
  - npm install -g firebase-tools
  - npm install firebase-admin
  - npm install firebase-functions
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
